import { tTask } from "@/types";
import { USERS } from "./users";

export const TASKS: tTask[] = [
  {
    id: 1,
    title: "Update Database",
    description: "Update customer database with new entries",
    status: "In Progress",
    priority: "Medium",
    createdAt: "1 May 2023 at 10:23 am",
    updatedAt: "3 May 2023 at 4:20 pm",
    users: [USERS[0], USERS[1]],
    contractor: USERS[2],
    author: USERS[3],
    imgSrc:
      "https://img.freepik.com/free-vector/vector-illustration-mountain-landscape_1441-72.jpg?w=2000",
    time: "02:45",
  },
  {
    id: 2,
    title: "Website Redesign",
    description: "Redesign the landing page of the website",
    status: "Not Started",
    priority: "High",
    createdAt: "2 May 2023 at 1:45 pm",
    updatedAt: "2 May 2023 at 2:00 pm",
    users: [USERS[4], USERS[3]],
    contractor: USERS[3],
    author: USERS[0],
    imgSrc: "https://via.placeholder.com/147",
    time: "01:34",
  },
  {
    id: 3,
    title: "Implement Security Patch",
    description: "Implement new security patch to the system",
    status: "In Progress",
    priority: "High",
    createdAt: "3 May 2023 at 8:00 am",
    updatedAt: "4 May 2023 at 9:00 am",
    users: [USERS[3]],
    contractor: USERS[2],
    author: USERS[1],
    imgSrc: "https://via.placeholder.com/149",
    time: "00:00",
  },
  {
    id: 4,
    title: "Server Maintenance",
    description: "Routine server maintenance and backup",
    status: "Completed",
    priority: "Low",
    createdAt: "4 May 2023 at 5:00 pm",
    updatedAt: "5 May 2023 at 9:00 am",
    users: [USERS[2], USERS[4]],
    contractor: USERS[0],
    author: USERS[1],
    imgSrc: "https://via.placeholder.com/149",
    time: "42:00",
  },
  {
    id: 5,
    title: "Bug Fixes",
    description: "Fix reported bugs in the system",
    status: "Not Started",
    priority: "Medium",
    createdAt: "5 May 2023 at 2:00 pm",
    updatedAt: "5 May 2023 at 2:30 pm",
    users: [USERS[1]],
    contractor: USERS[3],
    author: USERS[2],
    imgSrc: "https://via.placeholder.com/150",
    time: "00:12",
  },
];
