import { ResponsiveDrawer } from "@/components";
import { NavigationProvider, TaskProvider, ThemeProvider } from "@/providers";
import Image from "next/image";

export const metadata = {
  title: "Fyde Interview",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        style={{
          background: "#ffffff",
        }}
      >
        <ThemeProvider>
          <NavigationProvider>
            <TaskProvider>
              <ResponsiveDrawer
                logo={
                  <Image
                    src="/logo.png"
                    alt="Logo"
                    width={30}
                    height={30}
                    priority
                  />
                }
              >
                {children}
              </ResponsiveDrawer>
            </TaskProvider>
          </NavigationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
